// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx0iBqvK289s7tQQ2x2wZuRrBGrmTyXoE',
    appId: '1:941362651057:web:d5dfa369f272128f412790',
    messagingSenderId: '941362651057',
    projectId: 'flowery-app-add84',
    authDomain: 'flowery-app-add84.firebaseapp.com',
    storageBucket: 'flowery-app-add84.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGfK3wgcOQZoCLHsz4ydWjywb2MvkNJuY',
    appId: '1:941362651057:android:6d3808a23b1f9afd412790',
    messagingSenderId: '941362651057',
    projectId: 'flowery-app-add84',
    storageBucket: 'flowery-app-add84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZHgCee-hD05-jHhTayA7OoMBt9v9bZcM',
    appId: '1:941362651057:ios:cd33b5cd9746dca0412790',
    messagingSenderId: '941362651057',
    projectId: 'flowery-app-add84',
    storageBucket: 'flowery-app-add84.firebasestorage.app',
    iosBundleId: 'com.example.flowery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZHgCee-hD05-jHhTayA7OoMBt9v9bZcM',
    appId: '1:941362651057:ios:cd33b5cd9746dca0412790',
    messagingSenderId: '941362651057',
    projectId: 'flowery-app-add84',
    storageBucket: 'flowery-app-add84.firebasestorage.app',
    iosBundleId: 'com.example.flowery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx0iBqvK289s7tQQ2x2wZuRrBGrmTyXoE',
    appId: '1:941362651057:web:c529ea550c4dea53412790',
    messagingSenderId: '941362651057',
    projectId: 'flowery-app-add84',
    authDomain: 'flowery-app-add84.firebaseapp.com',
    storageBucket: 'flowery-app-add84.firebasestorage.app',
  );
}
