// Mocks generated by Mockito 5.4.4 from annotations
// in flowery/test/data/data_source/remote_data_source/auth/auth_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowery/data/api/auth_api/api_manger.dart' as _i3;
import 'package:flowery/data/model/auth/requests/sign_up_request_model.dart'
    as _i5;
import 'package:flowery/data/model/auth/response/sign_up_response_model.dart'
    as _i2;
import 'package:flowery/data/model/user_model.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSignUpResponseModel_0 extends _i1.SmartFake
    implements _i2.SignUpResponseModel {
  _FakeSignUpResponseModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiManger].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiManger extends _i1.Mock implements _i3.ApiManger {
  MockApiManger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SignUpResponseModel> signUp(
          _i5.SignUpRequestBodyModel? signUpRequestBody) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [signUpRequestBody],
        ),
        returnValue: _i4.Future<_i2.SignUpResponseModel>.value(
            _FakeSignUpResponseModel_0(
          this,
          Invocation.method(
            #signUp,
            [signUpRequestBody],
          ),
        )),
      ) as _i4.Future<_i2.SignUpResponseModel>);

  @override
  _i4.Future<String?> forgetPassword(Map<String, dynamic>? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [email],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> verifyResetCode(Map<String, dynamic>? resetCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [resetCode],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<_i6.UserModel?> logIn(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #logIn,
          [body],
        ),
        returnValue: _i4.Future<_i6.UserModel?>.value(),
      ) as _i4.Future<_i6.UserModel?>);
}
