name: PR Title Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate PR title
        run: |
          shell: bash
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_TITLE_REGEX="^(feat|fix|release|hotfix|build|test)\/FECOM-[0-9]+-[A-Za-z0-9\s-]+$"

          echo "Validating PR title: $PR_TITLE"

          if [[ ! "$PR_TITLE" =~ $PR_TITLE_REGEX ]]; then
            echo "Error: PR title '$PR_TITLE' does not match the required format."
            echo "Required format: type/FECOM-{TicketNum}-task name"
            exit 1
          fi

          echo "PR title is valid."